export const GET_CAPSULES_SUCCESS = "GET_CAPSULES_SUCCESS";
export const SEARCH_INPUT_CHANGE = "SEARCH_INPUT_CHANGE";
export const LANDING_PAD_SUBMIT = "LANDING_PAD_SUBMIT";
export const LANDING_PAD_SUCCESS = "LANDING_PAD_SUCCESS";
export const API_ERROR = "API_ERROR";
export const INIT_PAGE = "INIT_PAGE";
